# Generated by Django 4.2.4 on 2023-09-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('Contacticon', models.CharField(blank=True, max_length=150)),
                ('Contact_social_mob', models.CharField(blank=True, max_length=150)),
                ('Contactiadd', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='contact_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GetInTouch', models.CharField(blank=True, max_length=100)),
                ('detail', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='social_media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_icon', models.CharField(blank=True, max_length=100)),
                ('social_media_link', models.CharField(blank=True, max_length=150)),
            ],
        ),
    ]
