# Generated by Django 4.2.4 on 2023-08-31 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0005_education_experience_my_skills2_myservices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='aboutphoto',
            field=models.ImageField(blank=True, upload_to='about/profile'),
        ),
        migrations.AlterField(
            model_name='first_display',
            name='firstimage',
            field=models.ImageField(blank=True, upload_to='profile'),
        ),
    ]
